<li>
							<a class="picitem" target="_blank" href="[field:arcurl/]"><img src="[field:picname/]" widht="275" height="160"><em></em></a>

							<div class="tit">

								<h4><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h4>

								<span>[ [field:pubdate function="GetDateTimeMK(@me)" /] ]</span>

							</div>

							<p>[field:description/]……</p>

							<a href="[field:arcurl/]" target="_blank" class="more">+ VIEW MORE</a>

						</li>