<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150522/1-150522135S7.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/150522/1-150522135S7.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="6016";
$z[1][4]['height']="4000";
$z[2]=Array("img"," /uploads/allimg/150522/1-150522135T2.jpg ",242,387);
$z[2][4]['ddimg']="/uploads/allimg/150522/1-150522135T2.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="420";
$z[2][4]['height']="320";
$z[3]=Array("img"," /uploads/allimg/150522/1-150522135T2-50.jpg ",389,540);
$z[3][4]['ddimg']="/uploads/allimg/150522/1-150522135T2-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="420";
$z[3][4]['height']="320";
$z[4]=Array("img"," /uploads/allimg/150522/1-150522135T2-51.jpg ",542,695);
$z[4][4]['ddimg']="/uploads/allimg/150522/1-150522135T2-51.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="6016";
$z[4][4]['height']="4000";

?>