<?php
$z[0]=Array("field","",361,380);
$z[0][4]['name']="title";
$z[1]=Array("global","",381,407);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",448,477);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",517,575);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",738,773);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" class=\"innav3_a\">\r\n          <h3>[field:typename/]</h3>\r\n          <h4>Wine cellar air conditioning</h4>\r\n          </a> </li>\r\n        ",1011,1229);
$z[5][4]['type']="son";
$z[6]=Array("list","\r\n            <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"301\" height=\"183\" alt=\"\"/>\r\n              <div class=\"pro_div\">\r\n<!--\r\n                <h3>[field:title/] </h3>\r\n-->\r\n              </div>\r\n              <span></span></a></li>\r\n            ",1453,1758);
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",1805,1858);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[8]=Array("include","",1962,1999);
$z[8][4]['filename']="footer.htm";

?>