<?php
$z[0]=Array("field","",361,380);
$z[0][4]['name']="title";
$z[1]=Array("global","",381,407);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",448,470);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",510,561);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",886,921);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" class=\"innav3_a\">\r\n          <h3>[field:typename/]</h3>\r\n          <h4>Wine cellar air conditioning</h4>\r\n          </a> </li>\r\n        ",1159,1377);
$z[5][4]['type']="son";
$z[6]=Array("productimagelist","\r\n                <li style=\"display:block\"><img src=\"[field:imgsrc/]\" width=\"87\" height=\"68\" alt=\"\" /><span></span></li>\r\n                ",1634,1820);
$z[7]=Array("productimagelist","\r\n                <li style=\"display:block\"><img src=\"[field:imgsrc/]\" width=\"87\" height=\"68\" alt=\"\" /></li>\r\n                ",1929,2102);
$z[8]=Array("field","",2923,2941);
$z[8][4]['name']="body";
$z[9]=Array("field","",3104,3127);
$z[9][4]['name']="cc";
$z[10]=Array("field","",3289,3312);
$z[10][4]['name']="cs";
$z[11]=Array("prenext","",3457,3482);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",3513,3539);
$z[12][4]['get']="next";
$z[13]=Array("include","",3627,3664);
$z[13][4]['filename']="footer.htm";

?>