<?php
$z[0]=Array("field","",361,380);
$z[0][4]['name']="title";
$z[1]=Array("global","",381,407);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",448,470);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",510,561);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",886,921);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" class=\"innav_a\">\r\n          <h3>[field:typename/]</h3>\r\n          <h4>The enterprise news</h4>\r\n          </a></li>\r\n        ",1081,1288);
$z[5][4]['type']="son";
$z[6]=Array("field","",1415,1434);
$z[6][4]['name']="title";
$z[7]=Array("field","",1642,1660);
$z[7][4]['name']="body";
$z[8]=Array("include","",1763,1800);
$z[8][4]['filename']="footer.htm";

?>