<?php
$z[0]=Array("pagestyle","",0,90);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="1";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/160304/1-160304112946.png ",92,252);
$z[1][4]['ddimg']="/uploads/allimg/160304/1-160304112946.png";
$z[1][4]['text']="Virion-Serion";
$z[1][4]['width']="400";
$z[1][4]['height']="267";

?>