
<field:zt itemname="主题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:zt>

<field:nr itemname="内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nr>

<field:mc itemname="名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mc>

<field:name itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>
