<?php
$z[0]=Array("channelartlist","\r\n      <ul>\r\n        <li class=\"footli1\">\r\n          <h3><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h3>\r\n        </li>\r\n        {dede:channel type='son' noself='yes'}\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        {/dede:channel}\r\n      </ul>\r\n      ",87,461);
$z[0][4]['typeid']="top";
$z[0][4]['row']="4";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",519,603);
$z[1][4]['typeid']="26";
$z[2]=Array("global","",861,887);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",888,912);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("flink","\r\n          <li>[field:link /]</li>\r\n          ",998,1106);
$z[4][4]['titlelen']="202";
$z[4][4]['row']="20";
$z[4][4]['type']="text";

?>