<?php
$z[0]=Array("field","",361,380);
$z[0][4]['name']="title";
$z[1]=Array("global","",381,407);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",448,477);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",517,575);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",738,773);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" class=\"innav_a\">\r\n          <h3>[field:typename/]</h3>\r\n          <h4>Company introduction</h4>\r\n          </a></li>\r\n         ",1017,1226);
$z[5][4]['type']="son";
$z[6]=Array("field","",1318,1339);
$z[6][4]['name']="content";
$z[7]=Array("include","",1414,1451);
$z[7][4]['filename']="footer.htm";

?>