<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司简介';
$typeArr[34] = '脑脊液产品';
$typeArr[38] = '疫苗接种后免疫效果监测试剂';
$typeArr[37] = '产品优势';
$typeArr[3] = '企业文化';
$typeArr[6] = '新闻动态';
$typeArr[7] = '企业新闻';
$typeArr[8] = '售后支持';
$typeArr[9] = '产品介绍';
$typeArr[10] = '产品中心';
$typeArr[28] = 'ToRCH优生优育酶免诊断试剂';
$typeArr[25] = '营销网络';
$typeArr[26] = '联系我们';
$typeArr[29] = '呼吸道传染病检测试剂';
$typeArr[30] = '疱疹病毒检测试剂';
$typeArr[31] = '儿童疾病检测试剂';
$typeArr[32] = '质控品';
$typeArr[33] = '其他试剂产品';
?>