<?php
    require("../../footer-header/header.php")
?>


<!--新闻内容方面-->
<div id="news">

    <div class="time">2018.07.24</div>
    <div class="newsd">
          <h3>【报告】国产疫苗深度研究报告</h3>
          <!-- JiaThis Button BEGIN -->
          <div class="clearfix" style=" margin-top:10px; margin-bottom:10px; text-align:right;"> </div>
          <!-- JiaThis Button END -->
          <p>　</p><p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">根据EvaluatePharma估计，全球疫苗市场2016年销售规模超过275亿美元，这一估计与KaloramaInformation的估计(2015年全球疫苗市场276亿美元)非常接近，且疫苗市场规模增速超过药品市场整体增速。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">国际市场大部分份额集中到了少数企业手中。从企业结构看，默沙东、辉瑞、赛诺菲、葛兰素史克“四巨头”占据了全球超过80%的份额，四家主要企业份额和增速也大体相当。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S41GL.jpg" style="width: 640px; height: 491px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S432400.jpg" style="width: 640px; height: 434px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S450644.jpg" style="width: 640px; height: 345px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">从品种来看，同样少数“爆款品种”占据了市场大部分份额。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99); font-size: 15px;">从品种结构看，国际市场最大的几个品类是呼吸系统疫苗(肺炎球菌疫苗、脑膜炎双球菌疫苗、流感疫苗等)、人乳头瘤病毒(HPV)疫苗、水痘和带状疱疹疫苗、轮状病毒疫苗等。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S505948.jpg" style="width: 640px; height: 421px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(0, 0, 0); font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">重磅品种发展滞后:一些国际疫苗市场的重要品种在我国仍未上市或比例严重偏低(如HPV疫苗，13价肺炎球菌多糖结合疫苗、轮状病毒疫苗、四价流脑结合疫苗、四价流感疫苗等)</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">多联疫苗水平低，数量少:相比国际市场，我国多联疫苗品种十分有限。多联疫苗是未来的发展趋势，不仅节省疫苗接种的人工和成本，减少就诊时间和注射次数，降低婴幼儿痛苦和伤害，简化接种程序，具有重要意义。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99); font-size: 15px;">国内传统品种已经基本饱和空间主要依靠政策和结构变动。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S51T59.jpg" style="width: 750px; height: 510px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">狂犬疫苗:Vero细胞狂苗大概率仍是主流HDCV有望提升份额</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">我国狂犬病每十年出现一个小流行周期，二十年左右出现一个大流行周期。1990—2007年是中国狂犬病第3个大流行周期，发病率呈先下降后上升的倒抛物线趋势，2008—2014年再行走低。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">这一周期与防疫政策密切相关，如2001年流行率大幅提升，主要与浓缩疫苗停止使用代之以价格昂贵的纯化疫苗(比浓缩人用疫苗价格高6倍)有关。<img alt="" src="/uploads/allimg/180724/1-1PH41S551Z8.jpg" style="width: 750px; height: 469px;"></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">市场上销售的狂犬病疫苗主要分为三类:</span></strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">自1980年代我国研制成功地鼠肾原代细胞培养疫苗，1990年代后期Vero细胞培养疫苗上市，并对疫苗不断改进生产工艺，达到了与国际一致的经浓缩、纯化、冻干的优质细胞培养疫苗。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2015年，纯化冻干的人二倍体细胞疫苗国内上市，利用人二倍体细胞作为病毒培养基质制备狂犬病疫苗，免疫效果好，副作用少，但培养技术难度较大，生产成本高。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S605X3.jpg" style="width: 640px; height: 382px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">根据《中国狂犬病防治现状》，估计全国(不含港澳台)每年被动物伤害的人数超过4000万人，</span><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99);">目前国内年批签发量在1200-1500余万人份左右，渗透率已经达到35-40%左右，总批签发量也已经多年缺乏突破。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">近年来我国狂犬病发病人数不断走低，表明狂犬病防治和狂犬疫苗接种也已经达到较高水平。除非政策出现重大改变，对狂犬疫苗的需求总量难有高增长空间，狂犬疫苗批签发增长也会相对平稳。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99); font-size: 15px;">国内目前占主流的依然是Vero细胞人用狂犬病疫苗(CPRV)，大部分为五针接种法，辽宁成大狂苗产品除了5针法外，还获批“2-1-1”接种即可完成免疫。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S615340.jpg" style="width: 640px; height: 607px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S62cM.jpg" style="width: 640px; height: 481px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前使用的细胞培养狂犬病疫苗中,HDCV(人二倍体狂犬病疫苗)被公认为最佳疫苗。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">但我们认为总的来说，</span><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99);">未来可能Vero细胞狂苗仍将会是市场主流，HDCV比例有望取得一定提升。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S641P3.jpg" style="width: 640px; height: 499px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">水痘疫苗:同样基本饱和一针变两针是机遇</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">水痘疫苗过去也是国内市场规模最大的二类苗之一，目前国内水痘疫苗接种每人份基本为一针，</span><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99);">根据当前国内新生儿数量，如果实现100%渗透率估计，市场需求大约1700万支。而连续多年国内水痘批签发已经稳定在1500-1900万支左右，市场需求几近饱和。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前国内有活跃批签发记录的，主要是长春百克、长生生物、长春祈健、上海所等企业，格局也相对稳定。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SA1X1.jpg" style="width: 640px; height: 492px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2006年，美国疾病预防控制中心和美国儿科学会即开始推荐接种两针水痘疫苗，2017年广东等地也已经下发通知将14岁及以下儿童水痘疫苗接种程序，调整为自愿自费接种2剂次。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">水痘市场目前需求和供应已经相对稳定，未来市场的主要弹性，在于1针改2针的推广范围和落地速度。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">肺炎链球菌(Streptococcuspneumoniae，pneumococcus)简称肺炎球菌，是重要的呼吸道致病菌，肺炎球菌感染可以导致无症状的鼻咽部定植、不太严重的疾病(如鼻窦炎、中耳炎)和严重疾病(如脑膜炎、肺炎和脓毒血症等)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前市场上有两类肺炎链球菌疫苗，结合疫苗(如13价肺炎球菌多糖结合疫苗，PCV13)和多糖疫苗(如23价肺炎球菌多糖疫苗，PPSV23)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">PPSV23安全性良好，但是不能有效诱导&lt;2岁婴幼儿产生保护性免疫应答。在WHO和美国疾控中心CDC的建议中，PCV接种均优先于PPSV，PPSV主要用于2岁以上高风险人群和已经完成PCV基础免疫人群的补充免疫应答。</span></p>
<p style="margin: 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SF9149.jpg" style="width: 640px; height: 501px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">肺炎球菌多糖结合疫苗:超重磅品种国内空间很大</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">PCV是国际疫苗市场超重磅品种，辉瑞沛儿全球销售额近年维持在50-60亿美元规模，是全球销售规模最大的疫苗品种。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前国内PCV已经上市的仅辉瑞原研(沛儿7价PCV因注册证到期于2015年退出大陆市场，2016年底沛儿13获批重新回归)，获批适应症为6周龄至15月龄婴幼儿的主动免疫，以预防由肺炎球菌血清型1、3、4、5、6A、6B、7F、9V、14、18C、19A、19F和23F引起的侵袭性疾病(包括菌血症性肺炎、脑膜炎、败血症和菌血症等)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">沃森生物13价肺炎球菌多糖结合疫苗已经完成III期临床试验，目前申请新药生产的药品注册申请已经获得受理。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">民海生物(上市公司康泰生物全资子公司)13价肺炎球菌结合疫苗也已经进入III期临床试验。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">此外还有兰州所、科兴生物、智飞绿竹等企业获批临床。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">PCV国内渗透率很低:由于疫苗注册和供应能力等问题，沛儿在国内批签</span></strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">发一直维持在较低水平(除2014年外均未超过100万支)</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">发达国家PCV普及率极高，根据美国CDC统计，2012-2016年美国19-35月龄婴幼儿PCV3针接种率均超过90%，4针接种率超过80%。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">我国当前每年新出生人口在1600-1800万人左右，如渗透率城市达到50%，农村达到25%，则估计每年PCV市场需求空间可达670万人份/2680万支，年销售额90亿人民币以上(目前PCV13原研国内招标价为698元，国产PCV13价格按原研50%估计)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SH31E.jpg" style="width: 640px; height: 424px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">肺炎球菌多糖疫苗竞争相对激烈:</span></strong><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">目前国内PPSV竞争企业数目较多，有赛诺菲巴斯德、默沙东、成都所、沃森生物等企业已经上市，每年批签发量在200-900万支之间，此外还有数家企业产品已经处于上市申请及III期临床，预计未来竞争将继续加剧。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SJ15S.jpg" style="width: 640px; height: 400px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">人乳头瘤病毒疫苗:超重磅单品存量人群规模庞大</span></strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前全球已经上市的HPV疫苗主要有3种，分别是葛兰素史克(GSK)的双价重组人乳头瘤病毒疫苗(希瑞适，Cervarix)，以及默沙东(MSD)的四价/九价人乳头瘤病毒疫苗(佳达修，Gardasil/Gardasil9)，均是预防性疫苗，以非感染性的病毒样颗粒(VLPs)形式存在。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2016年7月，希瑞适在国内获批上市，适用于9-25岁的女性，采用3剂免疫接种程序，用于预防因高危型人乳头瘤病毒(人乳头瘤病毒(HPV)16、18型所致的宫颈癌、CIN和原位腺癌。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2017年5月佳达修四价苗国内获批。Gardasil和Gardasil9在美国获批适用于9-26岁的男性和女性，用于预防4/9种HPV引起的宫颈癌、阴道癌、外阴癌、肛门癌、相关癌前病变和上皮内瘤样病变，以及生殖器疣。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">在国内，佳达修疫苗获批用于20-45岁的女性接种，采用3剂免疫接种程序，适用于预防由16、18型人乳头瘤病毒(HPV)所致的宫颈癌，宫颈上皮内瘤样病变(CIN1/2/3)和原位腺癌(AIS)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">佳达修在国内由智飞生物独家代理，根据智飞生物与美国默沙东签署的协议，默沙东在取得四价HPV疫苗上市许可后，将向智飞生物独家供应该产品，并许可公司在协议区域内独家经销，联合推广该产品。双方基础采购计划为第一年度约11.4亿元，第二年度约14.83亿元，第三年度约18.53亿元。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SK4F5.jpg" style="width: 640px; height: 434px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">HPV市场空间:年增量数十亿级，存量数百亿级</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">由于发达国家青少年性活跃期开始较早，HPV疫苗接种普遍较早。根据美国CDC统计，美国17岁青少年HPV接种完成率已经达到47%(其中男性，女性59%，男性37%)。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">对我国每年增量市场的测算:我国目前仅获批女性适用人群，如果按照年新增到龄人群1600万，男女性别比例1:1(2017年末我国性别比例104.8:100，接近1:1)，按30%女性渗透率，单支疫苗售价800元计算，则每年增量人群接近250万人，增量市场超过50亿/年。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">对我国存量市场的测算:即使采用非常保守的年龄范围，考虑我国15-30岁女性人口(对应2010年普查7-22岁女性人口)，根据2010年第六次人口普查数据，按照城市40%，城镇25%，乡村10%渗透率估算，</span><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99);">潜在接种人群可达3100万人，市场规模超过600亿人民币。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">从批签发量来看，如按照3剂/人份计算，国内2018年1月HPV疫苗批签发量已经达到40万人份左右。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SP5A0.jpg" style="width: 640px; height: 438px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SQKN.jpg" style="width: 640px; height: 449px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">轮状病毒疫苗:年终端规模同样可达50亿人民币</span></strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">轮状病毒于1973年最早由Bishop用电镜从澳大利亚腹泻儿童肠活检上皮细胞内发现，形如车轮状，故命为“轮状病毒”。人和动物轮状病毒分为7组和两个亚群，其中A、B、C3组能引起人畜共患的腹泻。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">其中A组轮状病毒是国际旅行中常见的病毒感染性腹泻病原体，其感染呈世界性分布，也是婴幼儿腹泻最重要的病原。我国每年大约有1000万婴幼儿患轮状病毒感染性胃肠炎，约占2岁以下婴幼儿的1/4，是引起婴幼儿严重腹泻的最主要病原。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">国际市场轮状病毒主要有葛兰素史克的单价轮状病毒疫苗Rotarix(罗特律)和默沙东的五价轮状病毒疫苗RotaTeq(轮达停)，二者份额大致相当。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SRW14.jpg" style="width: 640px; height: 492px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SSQH.jpg" style="width: 640px; height: 499px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前国内上市仅有成都所的口服轮状病毒活疫苗罗特威，适用于2个月-3岁婴幼儿，需每年服用。国际轮状病毒产品也在进入国内的申报过程中。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SU1325.jpg" style="width: 640px; height: 221px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">根据美国CDC统计数据，美国婴幼儿轮状病毒疫苗接种率近年来稳定在70%以上。参考上述水平，</span><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; color: rgb(196, 157, 99);">如国内年均新生儿数按1700万估计，如能达到40%接种率，则国内轮状病毒市场空间超过2000万支/年。</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">B型流感嗜血杆菌(Hib)是引起小儿严重细菌感染的主要致病菌，可导致脑膜炎、肺炎、败血症、会厌炎、蜂窝组织炎、心包炎、脊髓炎等多种侵袭性疾病，曾是欧美国家导致细菌性脑膜炎的首位病原菌。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41SZGS.jpg" style="width: 640px; height: 318px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">脑膜炎球菌疫苗国内主要有多糖疫苗和结合疫苗两种</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">与肺炎球菌疫苗的情况类似，多糖疫苗只能适用于两岁以上的儿童与成人，而结合疫苗适用于2/3月龄以上的婴幼儿等对多糖疫苗无应答、低应答的人群。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">国内流脑疫苗当前年批签发规模约30亿元左右，我国A群流脑多糖疫苗和A群C群流脑多糖疫苗属于一类苗，而ACYW135和结合疫苗属于二类苗。因此A群和AC多糖疫苗虽然销量较大，如按销售额和货值计算，结合疫苗的市场份额超过50%。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前国内该领域申报注册竞争力较为激烈，不仅有众多上市产品，如ACYW135结合疫苗等申报中品种也有较多竞争者。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S923K9.jpg" style="width: 640px; height: 252px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">流感嗜血杆菌疫苗国内批签发格局较为稳定，且Hib疫苗和其他品种联合的多联疫苗今年来放量趋势较强。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S93Y53.jpg" style="width: 640px; height: 497px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41S951M4.jpg" style="width: 640px; height: 526px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12); font-weight: 700;">▌</span></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前使用的流感疫苗可分为灭活疫苗和减毒活疫苗两类</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">灭活疫苗可分为全病毒疫苗、裂解疫苗和亚单位疫苗。其中裂解疫苗能有效减少不良反应,保证良好的安全性、免疫原性和稳定性，广泛应用于儿童、成人和老年人。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">减毒活疫苗是一种降低了毒力并能在最佳适应温度生长的毒株,但是与其他病毒可能发生基因重配,得到毒力恢复的重配株;减毒活疫苗对2~8岁儿童有较好的保护作用，但对老人和免疫缺陷及免疫功能低下人群存在潜在危害。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">三价流感疫苗在国内非常成熟，由于疫苗有效期一年，每年批签发总量随着疫情波动变化较大。2009-2010年的全球甲流疫情将行业批签发规模推高至巅峰，而近年则不断回落。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41T00Q03.jpg" style="width: 640px; height: 407px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <img alt="" src="/uploads/allimg/180724/1-1PH41T025928.jpg" style="width: 640px; height: 512px;"></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">目前世界上获得批准使用的流感疫苗均为季节性流感疫苗，其中最为广泛使用的为三价灭活疫苗，包含两种危害较大的A型流感病毒(H1N1和H3N2毒株各一个)和一种B型流感病毒毒株。2013年-2014年，WHO开始推荐四价流感病毒，在传统的三价流感病毒之外增加了一种B型流感病毒。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;"><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;"><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box; word-wrap: break-word; line-height: 32px; letter-spacing: 0.544px; color: rgb(241, 12, 12);">▌</span></strong><strong style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">四价流感疫苗在国外已经上市，但在国内仍处于研发冲刺阶段</strong></span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2012年2月美国FDA注册批准鼻腔喷雾四价流感疫苗，由美国FluMist，Medlmmune疫苗公司研制。该疫苗为减毒活疫苗，含有二种A型流感和二种B型的不同谱系流感病毒。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">2012年7月20日美国FDA批准GSK四价流感疫苗Fluarix用于3岁以上儿童和成人的A型和B型流感的预防。该疫苗是覆盖4种流感病毒株(二种A型流感和二种B型)的裂解病毒的肌注疫苗。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">国内尚无四价裂解病毒疫苗上市。从事四价裂解病毒疫苗研发的企业多家，其中进度最为领先的是长生生物和华兰生物子公司华兰疫苗。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important; font-size: 15px;">从目前情况来看，领先企业年内获批，四价品种成功赶上流感疫苗接种高峰是大概率事件。</span></p>
<p style="margin: 1em 0px; padding: 0px; max-width: 100%; clear: both; min-height: 1em; color: rgb(51, 51, 51); font-family: -apple-system-font, BlinkMacSystemFont, &quot;Helvetica Neue&quot;, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei UI&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: 17px; letter-spacing: 0.544px; line-height: 27.2px; text-align: justify; widows: 1; box-sizing: border-box !important; word-wrap: break-word !important;">
    <span style="font-size:16px;"><strong><span style="margin: 0px; padding: 0px; max-width: 100%; box-sizing: border-box !important; word-wrap: break-word !important;">报告来源：国金证券 / 分析师：李敬雷&nbsp;</span></strong></span></p>
<div>
    &nbsp;</div>
 <p></p>
        </div>
</div>























<div id="footer" style="height: 295px">
    <div class="item">
        <ul>
            <li class="title"><img src="../../img/logo.png" height="50px"></li>
            <li><a href="../..//Diagnostics">赛润诊断主页</a></li>
            <li><a href="/Immunologics">赛润生物原材料主页</a></li>
        </ul>
    </div>
    <div class="item">
        <ul>
            <li class="title">关于我们</li>
            <li><a href="../../about.php#about1">公司简介</a></li>
            <li><a href="../../about.php#about2">发展历程</a></li>
            <li><a href="../../about.php#about3">企业文化</a></li>
            <li><a href="../../about.php#about4">产品品质</a></li>
        </ul>
    </div>
    <div class="item">
        <ul>
            <li class="title">联系我们</li>
            <li><a href="../../contact.php">联系方式</a></li>
            <li><a href="../../message.php">在线留言</a></li>
            <li><a href="../../hiring.php">招贤纳士</a></li>
        </ul>
    </div>
    <div class="item">
        <ul>
            <li class="title">友情链接</li>
            <!--            <li><a href="https://www.virion-serion.de">virion\serion</a></li>-->
            <li><a href="http://www.klonnewbio.com/">科隆生物</a></li>
            <li><a href="http://www.csmedlab.com/">中南检验</a></li>
            <li id="mpweixin">
                微信公众号
                <img src="../../img/mp.weixin.jpg" alt="">
            </li>
            <li><a href="https://www.who.int/" target="_blank">世界卫生组织</a></li>
            <li><a href="http://www.chinacdc.cn/" target="_blank">中国疾病预防控制中心</a></li>
            <li><a href="https://www.ecdc.europa.eu/" target="_blank">欧盟疾病预防与控制中心</a></li>
            <li><a href="https://www.cdc.gov/" target="_blank">美国疾病控制与预防中心</a></li>
            <li><a href="https://iivd.net/portal.php" target="_blank">小桔灯</a></li>
        </ul>
    </div>
</div>
<script src="../../js/general.js"></script>
</body>
</html>